apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitnesstracker-deployment
  labels:
    app: fitnesstracker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fitnesstracker
  template:
    metadata:
      labels:
        app: fitnesstracker
    spec:
      containers:
        - name: fitnesstracker
          image: ozihler/fitnesstracker:1
          ports:
            - containerPort: 8080

